# openapi2-functions.yaml
openapi: '3.0.0'
info:
  title: immediateInsights
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /immediateInsights:
    get:
      summary: get immediate figures from data in json format including state, num loans given, total amount dispursed, this only calls firestore db, no additional api calls are made 
      operationId: getInsights
      # x-google-backend:
      #   address: https://us-east4-forge-praetorian-sol.cloudfunctions.net/getImmediateInsights
      responses:
        '200':
          description: A successful response 
          content:
            application/json:
              schema:
                type: string
           

