# openapi2-functions.yaml
openapi: '3.0.0'
info:
  title: path-object api config
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /pathObject:
    post:
      summary: build  path object
      operationId: getPath
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArrayOfPaths'
      x-google-backend:
        address: https://us-east4-forge-praetorian-sol.cloudfunctions.net/getPathObject
      responses:
        '200':
          description: A successful response 
          schema:
            type: string
           

components:
  schemas:
    ArrayOfPaths: 
      title: array of path objects 
      type: object
      properties: 
        paths:
          type: array
          items:  
            $ref: '#/components/schemas/PathObject'
        commonParameters: 
          type: array
          items: 
            $ref: '#/components/schemas/Parameters'


    PathObject:
      title: create a path
      type: object
      properties:
        pathName:
          type: string
          description: Name of Path
        pathSpecifier: 
          type: object
          additionalProperties: 
            type: string
        pathOperations: 
            type: array
            items: 
              $ref: '#/components/schemas/Parameters'


    Parameters:
      title: create a param
      type: object
      additionalProperties:
        type: string