openapi: '3.0.0'
info:
  title: root yaml
  description: forge swagger
  version: 1.0.0
schemes:
  - http
produces:
  - application/json
paths:
  /immediateInsights: 
    $ref: './immediateInsights/openapi3-functions.yaml#/paths/~1immediateInsights'