# openapi2-functions.yaml
openapi: '3.0.0'
info:
  title: insightsOverTime
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /insightsOverTime:
    get:
      summary: get insights by month 
      operationId: getInsights
      # x-google-backend:
      #   address: https://us-east4-forge-praetorian-sol.cloudfunctions.net/getInsightsOverTime
      responses:
        '200':
          description: A successful response 
          content:
            application/json:
              schema:
                type: string
           

